# .github/workflows/terraform-apply.yml
name: 'Terraform Apply'

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  apply-dev:
    name: 'Terraform Apply Dev'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: dev
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_DEV_ACCOUNT_ID:role/github-actions-myproject-dev  # Update this
          aws-region: us-east-1
          role-session-name: TerraformApply

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=dev-myproject-terraform-state" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-lock-myproject-dev"

      - name: Terraform Apply
        run: |
          terraform apply \
            -var-file="environments/dev.tfvars" \
            -auto-approve

  apply-prod:
    name: 'Terraform Apply Prod'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: prod
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_PROD_ACCOUNT_ID:role/github-actions-myproject-prod  # Update this
          aws-region: us-east-1
          role-session-name: TerraformApply

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=prod-myproject-terraform-state" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-lock-myproject-prod"

      - name: Terraform Apply
        run: |
          terraform apply \
            -var-file="environments/prod.tfvars" \
            -auto-approve